# This is a basic workflow to help you get started with Actions
name: "Build and Deploy Site"
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Build Zola site with Nix Flakes
        uses: cachix/install-nix-action@v18
        with:
          install_url: https://github.com/nix-community/nix-unstable-installer/releases/download/nix-2.12.0pre20221116_62960f3/install
          extra_nix_config: |
            experimental-features = nix-command flakes
      - run: nix flake check
      - run: nix build --out-link build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          cname: micha.elmurphy.com
